version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: E-Learning
    environment:
      POSTGRES_DB: e_learning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
